name: Fix Missing Lock File

on:
  workflow_dispatch:

jobs:
  generate-lock-file:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    
    - name: Generate lock file
      run: pnpm install --frozen-lockfile=false
      
    - name: Commit lock file
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add pnpm-lock.yaml
        git commit -m "Add pnpm-lock.yaml file"
        git push